os: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.11.2\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - cmake --build . --config Release
